### ISSUE TITLE
Game Of Thrones Gopher

### ISSUE THREAD

**Issue by jbrockopp** [ashleymcnamara/gophers#13]
Could we get a Game of Thrones gopher created?

https://www.hbo.com/game-of-thrones

**Comment by ashleymcnamara** [comment]
https://github.com/ashleymcnamara/gophers/blob/master/GOT_Gopher.png

**Comment by jbrockopp** [comment]
@ashleymcnamara you deserve unlimited karma for this one 👍 

What's crazy is my coworkers and I were just talking about this today!
