### ISSUE TITLE
Separate space gophers

### ISSUE THREAD

**Issue by apiarian** [ashleymcnamara/gophers#6]
I've put together this screensaver of twirling space gophers, inspired by the video loops at the 2017 GopherCon. https://github.com/apiarian/space-gophers . But it would be 1000x more fabulous if there were more space gophers that could be used. Unfortunately I'm quite inept at image editing, so I wouldn't trust myself to try to split the various existing space gopher images.

Could you please add some separated space gophers to this repo?

**Comment by ashleymcnamara** [comment]
This what you were looking for? :)
![bluegopher](https://user-images.githubusercontent.com/3139143/30776266-17b84692-a069-11e7-99f8-c0a6dba4b128.png)
![gophercon1](https://user-images.githubusercontent.com/3139143/30776269-17b8d6ac-a069-11e7-8618-4aa56149dd3a.png)
![pinkgopher](https://user-images.githubusercontent.com/3139143/30776268-17b89fb6-a069-11e7-829a-0e9caf3b69bf.png)
![purplegopher](https://user-images.githubusercontent.com/3139143/30776267-17b8656e-a069-11e7-81b4-3fbb43c2d2ad.png)
![yellowgopher](https://user-images.githubusercontent.com/3139143/30776270-17b97094-a069-11e7-9a40-0072e890b198.png)

**Comment by apiarian** [comment]
That's absolutely perfect!! thanks so much @ashleymcnamara !

**Comment by ashleymcnamara** [comment]
No problem! Closing this one now :)

**Comment by apiarian** [comment]
I've incorporated these gophers into the space-gophers screensaver. In case you like to keep track of where the gophers journey to. =D

**Comment by JBhrayn** [comment]
Hi, @ashleymcnamara . I'm wondering if I could use your image of astronaut gopher for non-commercial purposes. I’ll be sure to give you full credit.

**Comment by Kush238** [comment]
Hey @ashleymcnamara ,

I have published a Blog/Article, and I have used one of the Golang Space Gopher so Go.dev or Google holds the copyright for this all Golang Space Gophers?

Because I have to mention the copyright information for this in my Blog/Article.

Thanks in advance : )
